// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7F4Hjqs9K3R2qu1AJ8eobgdW_eXHTlDw',
    appId: '1:607666586504:web:0141bd10c4ca3fde58303d',
    messagingSenderId: '607666586504',
    projectId: 'rync432',
    authDomain: 'rync432.firebaseapp.com',
    storageBucket: 'rync432.firebasestorage.app',
    measurementId: 'G-QMXEDY6BK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwl3JlTDzbdCEpHlBM-jb6_k1KZ7SO1tY',
    appId: '1:607666586504:android:e1b67edc1c08371558303d',
    messagingSenderId: '607666586504',
    projectId: 'rync432',
    storageBucket: 'rync432.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7F4Hjqs9K3R2qu1AJ8eobgdW_eXHTlDw',
    appId: '1:607666586504:ios:0141bd10c4ca3fde58303d',
    messagingSenderId: '607666586504',
    projectId: 'rync432',
    storageBucket: 'rync432.firebasestorage.app',
    iosBundleId: 'com.aizatfir.focusClock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7F4Hjqs9K3R2qu1AJ8eobgdW_eXHTlDw',
    appId: '1:607666586504:ios:0141bd10c4ca3fde58303d',
    messagingSenderId: '607666586504',
    projectId: 'rync432',
    storageBucket: 'rync432.firebasestorage.app',
    iosBundleId: 'com.aizatfir.focusClock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7F4Hjqs9K3R2qu1AJ8eobgdW_eXHTlDw',
    appId: '1:607666586504:web:0141bd10c4ca3fde58303d',
    messagingSenderId: '607666586504',
    projectId: 'rync432',
    authDomain: 'rync432.firebaseapp.com',
    storageBucket: 'rync432.firebasestorage.app',
    measurementId: 'G-QMXEDY6BK5',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyB7F4Hjqs9K3R2qu1AJ8eobgdW_eXHTlDw',
    appId: '1:607666586504:web:0141bd10c4ca3fde58303d',
    messagingSenderId: '607666586504',
    projectId: 'rync432',
    authDomain: 'rync432.firebaseapp.com',
    storageBucket: 'rync432.firebasestorage.app',
    measurementId: 'G-QMXEDY6BK5',
  );
}
