name: Sadar Multiplatform Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - name: Build Android APK
        run: flutter build apk --release --android-skip-build-dependency-validation
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sadar-Android-APK
          path: build/app/outputs/flutter-apk/app-release.apk

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - name: Build Linux
        run: |
          flutter build linux --release
          cd build/linux/x64/release/bundle
          tar -czvf ../../../../../Sadar-Linux-x64.tar.gz .
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sadar-Linux-x64
          path: Sadar-Linux-x64.tar.gz

  build-windows:
    runs-on: windows-latest
    env:
      CMAKE_POLICY_VERSION_MINIMUM: "3.5"
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - name: Build Windows
        env:
          CMAKE_POLICY_VERSION_MINIMUM: "3.5"
        run: |
          flutter build windows --release
          Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath Sadar-Windows-x64.zip
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sadar-Windows-x64
          path: Sadar-Windows-x64.zip

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - name: Build Web
        run: |
          flutter build web --release
          cd build/web && zip -r ../../Sadar-Web.zip .
      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sadar-Web
          path: Sadar-Web.zip
